### ISSUE TITLE
better browser extension & add-ons recommendations

### ISSUE THREAD

**Issue by elijh** [riseupnet/riseup_help#139]
The list on https://help.riseup.net/en/security/network-security/better-web-browsing is pretty out of date.

What browser extensions would we now recommend? My proposal:

## Firefox

Recommended:

* HTTPS Everywhere https://www.eff.org/https-everywhere
* uBlock https://addons.mozilla.org/en-US/firefox/addon/ublock/
* Self Destructing Cookies https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/
* Disable Flash. Alternately, if you want to use Flash occasionally, install:
 * ~~Flash Block. this will allow 'click to play' even for latest flash version. https://addons.mozilla.org/en-US/firefox/addon/flashblock/~~ I think firefox just lets you select 'click to activate' now, like chrome.
 * Better Privacy: needed to remove LSO or "flash cookies".  https://addons.mozilla.org/en-US/firefox/addon/betterprivacy/
* Disable Java

Additional protection (but likely to cause compatibility problems on many websites):

* Referrer privacy, either:
 * RefControl https://addons.mozilla.org/en-US/firefox/addon/refcontrol/
 * Smart Referrer https://addons.mozilla.org/en-US/firefox/addon/smart-referer/
* Canvas Blocker https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/
* NoScript https://addons.mozilla.org/en-US/firefox/addon/noscript/
* RequestPolicy https://addons.mozilla.org/en-US/firefox/addon/requestpolicy/
* Random Agent Spoofer https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/

Not recommended:

* TrackMeNot: an interesting idea to generate bogus search data, but better to just use DuckDuckGo.
* Better Privacy: This is only needed if you have Flash installed or enabled. It is used to clean up LSO or the so called "flash cookie".
* AdBlockPlus: uBlock is much better.
* Privacy Badger: uBlock already blocks tracking, as well as ads. Privacy Badger does do social media widget replacement, which could be a reason to recommend installing it. Privacy Badger might be useful if there is a new tracking network that uBlock is not yet configured for, but this happens rarely.
* Disconnect: No benefit over other free software alternatives. It is unclear where the Disconnect company is headed, since if you go to their website there is no link to install the Firefox extension anymore, they just want you to install their VPN.
* Ghostery: Closed source, and no benefit over the free software alternatives.

## Chrome

Recommended

* uBlock

**Comment by elijh** [comment]
here are two free software user agent switchers:

* https://github.com/dillbyrne/random-agent-spoofer/ (Firefox)
* https://github.com/tarampampam/random-user-agent (Chrome)

I am using the latter, and it works well. Although some sites, like github, will break if it thinks you are using an older browser.

**Comment by elijh** [comment]
> I like the idea of disabling flash more than recommend better privacy

+1

**Comment by elijh** [comment]
oh, nevermind, i guess i was just agreeing to you agreeing with me. :)

**Comment by elijh** [comment]
Why has no one written a simple all-in-one that disables referrer, disables flash, disables third party cookies, and sets a generic user agent string? I want something that you install and then it sets good defaults and warns you if you ever change them.

**Comment by elijh** [comment]
prism-break recommendations:

https://prism-break.org/en/categories/gnu-linux/#web-browser-addons

**Comment by xinomilo** [comment]
refcontrol for mozilla (included in debian repos) is a nice referrer addon, for firefox only...
http://www.stardrifter.org/refcontrol
user-agent-switcher (firefox only) for changing default user agent.. 
http://chrispederick.com/work/user-agent-switcher/

adblock edge for firefox, adblock(?) for chrome, do the adblocking part nicely.
tried ghostery in the past with both chrome/firefox, but lots of memory used and random crashes.. got rid of it and browsing was fun again :)  

cookies deletion (on exit), and flash plugin can be disabled manually via regular browser options (not about:config), maybe thats a better "tip", than just filling the browser with addons (?)

**Comment by elijh** [comment]
this seems better than adblock for chrome: https://github.com/gorhill/uBlock

**Comment by bruo** [comment]
And now it supports firefox too! https://github.com/gorhill/uBlock/releases :D

**Comment by elijh** [comment]
Another long discussion on this very topic: https://www.reddit.com/r/privacy/comments/31ikb0/firefox_addons_what_to_keep_and_what_to_get_rid_of/

**Comment by cooperq** [comment]
Add https-everywhere, canvas fingerprint block, and webrtc block from chromium  
There is also the chameleon plugin which tries to detect and block fingerprinting but it does tend to break some things still.

**Comment by cooperq** [comment]
I would say that one advantage of privacy badger over µblock is that privacy badger will block third party resources from setting/getting cookies and getting referrers, which µblock will not block at all. For example maps.google.com, amazonaws, cloudflare, etc.

**Comment by taggart** [comment]
I would like to recommend switching search to DuckDuckGo. They have a page that's a good start at
https://duck.co/help/desktop/adding-duckduckgo-to-your-browser
But I would recommend:
* installing their browser plugin
* going into the search settings and deleting (or at least disabling) gmail/yahoo/bing/etc

**Comment by elijh** [comment]
resolved by https://github.com/riseupnet/riseup_help/pull/213
