### ISSUE TITLE
No instructions for verifying keyserver pool certificate

### ISSUE THREAD

**Issue by xloem** [riseupnet/riseup_help#145]
Hi,

The instructions at https://help.riseup.net/en/security/message-security/openpgp/best-practices/#use-the-sks-keyserver-pool-instead-of-one-specific-server-with-secure-connections indicate to verify the fingerprint of the sks-keyservers.net CA certificate.

However, there the indication of how to do this is missing.  The instructions to verify link to https://sks-keyservers.net/verify_tls.php which gives the fingerprints, but does not say how to verify them.

It would also be good to include these things in the page itself, in case the link dies.

**Comment by hucste** [comment]
It possible to verify cert CA, by 3 ways : 

Both with openssl, as:
- Verify: **_openssl verify -trusted file_CA -check_ss_sig file_CA_**
- Inspect: **_openssl x509 -in file_CA -noout -text | grep "X509v3 Subject Key Identifier" -A1 | tail -n1 | tr -d ' '_**; - and compare-it with the fingerprint X509 writed into page 'verify_tls'.

Third solution with gpg: **_gpg --verify file_CA.asc file_CA_**

**Comment by kradan** [comment]
since this help page is being reviewed (#451) it may be worth adding an instruction for non-nerds, which is quite tricky (compare the [wordy instructions to verify riseup's certificate](https://riseup.net/en/security/network-security/certificates)).

**Comment by micah** [comment]
The gnupg best-practices document has been deprecated, so we are closing these issues related to it.
