### ISSUE TITLE
Switch recommended extension uBlock for uBlock Origin

### ISSUE THREAD

**Issue by bruo** [riseupnet/riseup_help#221]
Well, in a bad timing thing there was some issues and drama related to uBlock. It seems uBlock was developed by several people but some weeks ago one of the main developers decided to take over the extension and put some donate buttons and saying it was made from him.

Now there are two uBlock extensions, one made by gorhill (uBlock Origin) and one made by Chris AlJoudi (uBlock). None of them is the original one or a fork by one, but the take over by Chris seems to be a bad move thinking about ethics and the future of the project (as it looks for monetization). 

gorhill's uBlock Origin keeps the manifesto of "Free. Open source. For users by users. No donations sought." as for the developers seems the only way to make this kind of extension good (compared with the history of adblock). 

So, for probably only ethical reasons I think it's a good idea to promote gorhill's addon instead of Chris one. As none is a fork or the main one, i guess it's totally doable.

You can read a more of the drama here:
https://www.reddit.com/r/linux/comments/39quzj/chris_aljoudis_ublock_not_gorhills_ublock_origin/
https://en.wikipedia.org/w/index.php?title=UBlock&type=revision&diff=662527440&oldid=662107368
https://www.reddit.com/r/chrome/comments/32ory7/ublock_is_back_under_a_new_name/cqd5ayy

gorhill's ublock or "uBlock Origin": https://github.com/gorhill/uBlock

**Comment by dtto** [comment]
I will admit that I was unaware of the issue, but given guido's writeup, I support making this change. Does anyone feel differently?

**Comment by dtto** [comment]
This has been changed.
