### ISSUE TITLE
Add documentation for mutt

### ISSUE THREAD

**Issue by pickfire** [riseupnet/riseup_help#224]
Hi, I hope that I can help to add documents for mutt email client to use with riseup and tor. Can I create a pull request?

**Comment by micah** [comment]
Ivan Tham <notifications@github.com> writes:

> Hi, I hope that I can help to add documents for mutt email client to use with riseup and tor. Can I create a pull request?

Great! You can of course create a pull request!

**Comment by pickfire** [comment]
Is there anyone who have write access to the repository other than @micah?

**Comment by micah** [comment]
Ivan Tham <notifications@github.com> writes:

> Is there anyone who have write access to the repository other than @micah?

yes, many people do

**Comment by pickfire** [comment]
Why should not riseup help use markdown or restructured text which is easy to learn?

**Comment by elijh** [comment]
textile is no harder to learn, and it is more powerful. markdown has better code modifiers, but otherwise textile is pretty good.

**Comment by pickfire** [comment]
Now I only know that riseup_help uses textile. I hope there is a contributing saying how to contribute to riseup_help and what markup language is it to let others contribute easily.

**Comment by e0i** [comment]
Please merge this pull request. A walkthrough for mutt was one of the first things I had looked up at riseup documentation.

**Comment by pickfire** [comment]
I hope so, I had created a pull request but it had not been merged.

**Comment by elijh** [comment]
ok, merged, sorry for the delay.
