### ISSUE TITLE
Adding info about anonymous remailer

### ISSUE THREAD

**Issue by pickfire** [riseupnet/riseup_help#234]
http://www.inventati.org/en/stuff/man_anon/remailer.html

**Comment by trinicity** [comment]
@pickfire What are these? Are these suggestions or are you noting things you are working on? I am hoping to contribute also.

**Comment by pickfire** [comment]
I don't have enough knowledge about these. I am just suggesting. I hope you can work on it and make it to be easier understandable to a newbie.

**Comment by pickfire** [comment]
Are you Trintin Boskovich <trintin@riseup.net>?

**Comment by trinicity** [comment]
Yes. These are the posts I asked about.

**Comment by kradan** [comment]
The mentioned service is listed on the page [radical servers](https://help.riseup.net/en/security/resources/radical-servers).

If there is some more info on remailers in general, we could probably integrate that to the page on  [message security](https://we.riseup.net/en/security/message-security)

It is worth mentioning, that remailers are a [subject of legal investigations](https://help.riseup.net/en/about-us/press/fbi-seizes-anonymous-remailer), so it could be risky for Riseup to specially advertise (link) those services.

@pickfire, should this issue stay open?

**Comment by pickfire** [comment]
@kradan This is an old issue, I think I will close it since it's not very secure like you say and it is an old issue.

Yeah, we could also integrate it into [message security](https://we.riseup.net/en/security/message-security)
