### ISSUE TITLE
what's up with privacy badger?

### ISSUE THREAD

**Issue by anarcat** [riseupnet/riseup_help#238]
why is privacy badger necessary, on top of ublock? the docs say:

> Privacy Badger dynamically detects attempts to track your browsing behavior and blocks content from these trackers. Privacy Badger is not designed to stop ads, so it is not a replacement for uBlock, but it includes some security features that uBlock does not have.

What are those security features exactly?

**Comment by elijh** [comment]
cooper said:

> I would say that one advantage of privacy badger over µblock is that privacy badger will block third party resources from setting/getting cookies and getting referrers, which µblock will not block at all. For example maps.google.com, amazonaws, cloudflare, etc.

also, the hope with privacybadger is that it is also able to detect tracking and block tracking sites that no one knows about yet and have not shown up on any block list.

on the other hand, i was not heartened by peter's response to my request that privacybadger prevent IP address leakage via WebRTC. i would be fine with removing privacybadger if we determine that there is in practice no effective benefit.

**Comment by anarcat** [comment]
well, i guess i don't see the benefit over uMatrix or request policy, basically.

uMatrix can disable third-party cookies and referers...

**Comment by xHN35RQ** [comment]
ublock has a dynamic filtering mode which blocks all 3rd-party by default. uMatrix blocks ALL 3rd-party cookies and referrers by default.

ublock can block IP leakage via WebRTC. Also, plugins by @ChrisAntaki are handy if you need addons to block WebRTC leakage, plugin enumeration and link leakage: https://addons.mozilla.org/en-US/firefox/user/ChrisAntaki/

**Comment by elijh** [comment]
the question is not if umatrix is awesome and should be recommended, but at what level.

the current write up has this:

level 1: ublock and privacy badger
level 2: umatrix

I think this is probably appropriate, since ublock and privacy badger are easy, work fine without any user input, won't break much. privacy badger also has nice user friendly replacements for the facebook/twitter/g+ share/like buttons that allows you to enable them if you want. 

umatrix is obviously the best thing to install if you are a user who wants to go beyond casual anti-tracking measures, but it is not at all designed for a general audience like ublock and privacy badger.

for it to make sense to entirely remove privacy badger from the recommendations, we would need to conclude there is no privacy benefit over ublock. what is this dynamic filtering mode? I don't see anything about it in the ublock options panel.

**Comment by anarcat** [comment]
i am not sure about this. out of the box, umatrix isn't too intrusive and can work well without breaking sites out of the box, in the default configuration. it enables good privacy protections, similar to privacy badget, if i understand correctly, out of the box, but *enables* users to do much more.

i think it would be fine to split this in two levels, but i don't see the point in privacy badger, really, if umatrix can do it all, and more.

**Comment by elijh** [comment]
To clarify, I am perfectly fine with recommending that people DON'T use privacy badger, if there are good reasons for this, but I don't think we have those reasons yet.

I like the idea of privacy badger, but I was not at all happy about their response the the WebRTC ip leakage.

**Comment by elijh** [comment]
i think gorhill's comment is helpful: https://github.com/gorhill/uMatrix/issues/32#issuecomment-61375201

> There are significant differences aside the ones you mention.

> Matrix-based filtering and its inheritance model (cell/rows/columns/scopes) can't be obtain with uBlock. uBlock follows ABP-filtering semantic, which is very simple:

> * Allow everything
>   * Unless there is a matching block filter
>     * Unless there is a matching allow filter
> Then it stops there. You can't override beyond this.

> There is no such restriction with matrix-filtering, it is fully hierarchical with no limit, and since it's written from the ground up this way, it far more efficient than pattern-based filtering. However, a higher granularity can be obtained with pattern-based filtering. So they complement each other in a way.

> But a majority of users just want an install and forget blocker, and this is uBlock. Power users however like to be fully informed about what web pages do, and be able to act on that information with a tool that makes it all easy, this is uMatrix.

> Just like RequestPolicy can't fully replace Adblock Plus and vice versa, and using one doesn't prevent using the other.

**Comment by xHN35RQ** [comment]
Wiki pages on uBlock Dynamic Filtering: https://github.com/chrisaljoudi/uBlock/wiki/Dynamic-filtering

Perhaps one way to approach this is offer 2 tiers and group addons together according to level of user involvement. Privacy Badger, ABP, uBlock and others would fall under Tier 1: Install and Forget it.

Tier 2 is Install and Monitor - this would be uBlock with dynamic filtering, uMatrix, NoScript, and RequestPolicy and these types of plugins which require user participation.

uBlock + Privacy Badger makes sense. uBlock Dynamic Filtering + Privacy Badger is redundant.

**Comment by elijh** [comment]
sorry for the delay. i like this suggestion and have updated the text in d380a2ec9b51b8c992dbbdd899dd1ce3a6dde371

**Comment by xHN35RQ** [comment]
Nice. uBlock default mode has been much improved of late. It can now do the following:

* Disable pre-fetching (to prevent any connection for blocked network requests)
* Disable hyperlink auditing/beacon
* Prevent WebRTC from leaking local IP addresses

**Comment by elijh** [comment]
> Prevent WebRTC from leaking local IP addresses

sadly still not enabled by default

**Comment by xHN35RQ** [comment]
> sadly still not enabled by default

Ah true! Good point.
