### ISSUE TITLE
WebRTC Blocking

### ISSUE THREAD

**Issue by manhack** [riseupnet/riseup_help#243]
I wonder why the WebRTC IP leak problem is not mentioned on the Better Web Browsing
Help page, as it is on this manual (which is really interesting, btw)  : https://gist.github.com/atcuno/3425484ac5cce5298932

WebRTC has a major privacy issue in that it can be abused to leak the internal IP address of users. This is very useful for advertisers who wish to develop very unique identifiers for users. It can also be abused to deanonymize users that whom utilized VPNs and/or Tor (1, 2, 3) in order to hide their true identity.

To block WebRTC in Chrome you must install this plugin.
https://github.com/rentamob/WebRTC-Leak-Prevent
https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml

To disable WebRTC in Firefox:
Enter "about:config" in the URL bar
Find the key of "media.peerconnection.enabled"
Set the value to "false"

To test if the plugin is operating correctly, visit this website and make sure that your local IP address does not appear.
https://diafygi.github.io/webrtc-ips/

**Comment by elijh** [comment]
I was trying to encourage Privacy Badger to fix the problem, see https://github.com/EFForg/privacybadgerchrome/issues/332 and https://github.com/EFForg/privacybadgerfirefox/issues/394

But, I didn't get very far... Peter feels that VPN/Tor users are a small minority, but I bet they constitute a much bigger percentage of PrivacyBadger users than he imagines.

ublock has a webrtc fix, which was not enabled by default last time i checked. i would like to just continue to recommend people use ublock, and add a note about turning on webrtc blocking.

**Comment by elijh** [comment]
ok, resolved by dc5cce0e0ab6db036896285b0113ff3dcc1a4be3
