### ISSUE TITLE
 Usage Agreement for Mail Accounts page pertinence

### ISSUE THREAD

**Issue by baldurmen** [riseupnet/riseup_help#288]
Hi!

While browsing through the git repo looking for pages to translate, I found the [Usage Agreement for Mail Accounts](https://help.riseup.net/en/email/usage-agreement) page.

It is not accessible by browsing menus on h.r.n and seems to contain quite redundant information.

If it is to be kept, you should add a nav link to it somewhere (and actualize the information on it). If not, it should be deleted.

**Comment by kradan** [comment]
The usage agreement is linked on the pages [email](https://help.riseup.net/en/email#frequently-asked-questions-faq) and [creating lists](https://help.riseup.net/en/lists/list-admin/configuration/creating-lists/#who-can-create-a-list). To be honest it is not very prominently linked.

I could add a nav_link, but it may be better to keep the navigation simple.

What do you (and others) think?

**Comment by kradan** [comment]
meanwhile i vote for closing this in favor of more urgent issues

**Comment by baldurmen** [comment]
No relevant anymore, closing!
