### ISSUE TITLE
Add steganography method

### ISSUE THREAD

**Issue by pickfire** [riseupnet/riseup_help#293]
Hi, I saw a nice article mentioning about using plain LUKS on top of plain LUKS for block encryption in https://www.linuxvoice.com/download-linux-voice-issue-15/

I hope that it can redirect it to the nice article.

**Comment by sqil2019** [comment]
Can you provide some example text that would be included? This link doesn't seem to work any longer.

**Comment by pickfire** [comment]
https://www.linuxvoice.com/issues/015/Linux-Voice-Issue-015.pdf it still works though, just some certificate issues.

**Comment by micah** [comment]
If you want to provide a pull request to make the changes, please do so. Thanks for the suggestion though!
