### ISSUE TITLE
riseup.net uses an invalid security certificate

### ISSUE THREAD

**Issue by kradan** [riseupnet/riseup_help#319]
since today the riseup.net SSL-certificate is outdated.

Tor Browser
> riseup.net uses an invalid security certificate.
>The certificate expired on 27.05.2016 23:59. The current time is 28.05.2016 10:08.
> (Error code: sec_error_expired_certificate)

Mozilla Firefox
> help.riseup.net uses an invalid security certificate.
> The certificate expired on 28.05.2016 01:59. The current time is 28.05.2016 11:24.
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

It is still possible to load the page with for example elinks as the expiration date is neither checked nor shown (press '=').

**Comment by micah** [comment]
Hi, the cert has been replaced!
