### ISSUE TITLE
Design refactoring ideas

### ISSUE THREAD

**Issue by just1602** [riseupnet/riseup_help#351]
I have some questions / ideas about the help.r.n design and I'd like to discuss them with you before jump into the code and waste time to code things that may be rejected. :P

### General

* Change bootstrap link color to be the same has the header color or the U color in the logo

### Status updates

Do you think is there a way to hide a part of the status updates and than keep the page a decent length or move them back to status.r.n?

### Email and list links

It could be nice to find a way to make links (Get help on mail.; Login to webmail.; Request an account.; Reset lost password.; Change my settings.) easier to read and give them a better disposition.

### Footer

* Rearrange content
* Remove system status
* make a shorter and more simple link to invite people to contribute to the pages
* Add link to the social medias accounts, irc and a link to the contact page for email key informations

What do you think about that, have you other ideas, comments, etc !?? :)

**Comment by kradan** [comment]
most of them appear uncritical and could be tried out on a new branch.

I also thought about the news feed and how to translate this. Translating the current news partial would break the concept as news wouldn't show up on the translation. It would be possible to push old news to an status archive page and only keep 'news' of the last weeks. Then old messages could be translated on a separate page.

**Comment by just1602** [comment]
@kradan  it's sure gonna be on a new brench. ;)

For the status archives, it's sound good to me and it'll allow us to avoid javascript and stuff like that.

**Comment by elijh** [comment]
> Change bootstrap link color to be the same has the header color or the U color in the logo

is the feeling that the links are too light?

> Do you think is there a way to hide a part of the status updates and than keep the page a decent length or move them back to status.r.n?

This is easy to implement. 

> It could be nice to find a way to make links (Get help on mail.; Login to webmail.; Request an account.; Reset lost password.; Change my settings.) easier to read and give them a better disposition.

I have done this, but not checked it in yet. I keep meaning to finish it.

> Remove system status

+1

> make a shorter and more simple link to invite people to contribute to the pages

+1

> Add link to the social medias accounts, irc and a link to the contact page for email key informations

this page? https://help.riseup.net/en/about-us/contact

**Comment by elijh** [comment]
>> Do you think is there a way to hide a part of the status updates and than keep the page a decent length or move them back to status.r.n?
> This is easy to implement.

To clarify:

step 1. move the status updates to a section of the site, which each update a separate page. then each one can be translated independently.

step 2. write a 'layouts/status' partial to display each status page.

step 3. insert this on the home page

````
= recent_summaries(:path => '/path/to/status/, :limit => 10) do |page|
    = render :partial => 'layouts/status', :locals => {:page => page}
```` 

This is how https://github.com/leapcode/leap_se works.

**Comment by elijh** [comment]
> It could be nice to find a way to make links (Get help on mail.; Login to webmail.; Request an account.; Reset lost password.; Change my settings.) easier to read and give them a better disposition.

OK, I have deployed my changes to the front page. Still could use some improvement, but better than before.

**Comment by just1602** [comment]
Nice, I don't have internet access, except at work.. I check this ASAP!
