### ISSUE TITLE
Modification at K-9 Mail 

### ISSUE THREAD

**Issue by aldobelus0** [riseupnet/riseup_help#373]
I don't know if this is the precise place to left this matter. Forgive me if it's not...
The link to the place is: [(https://riseup.net/es/email/clients/k9)], point 6.

At the help page for K-9 Mail settings -for Android- there is a detail that needs to be changed. 
At the second page, where you configure the IMAP settings, it's mandatory to insert your complete email address (user@riseup.net), not only your user name. It's needed at this point and at the next page, the SMTP one.
I would corrected myself If make a correction was easier, but it looks difficult to me, I'm sorry.

**Comment by kradan** [comment]
> At the help page for K-9 Mail settings -for Android- there is a
> detail that needs to be changed. At the second page, where you
> configure the IMAP settings, it's mandatory to insert your complete
> email address (user@riseup.net), not only your user name.

The help page says:

4) Enter your riseup email address 'youruser@riseup.net' and password

Please correct, if that is not what it should be.

**Comment by aldobelus0** [comment]
As I said before, I'm talking about the step 6, where the page says: "6) Your username, password, and server should be prefilled in, if not, fill them in with ‘youruser’ and ‘yourpassword’ and mail.riseup.net".
Well, it's prefilled in, but only with the username. If you let it so, the setting will not be right, and appears an error message.
If you do it as you can see at the picture -following the link below- and add the red text in the page that appears after selecting IMAP, it will be ok. Is clearer now? 
[https://b2aeaa58a57a200320db-8b65b95250e902c437b256b5abf3eac7.ssl.cf5.rackcdn.com/media_entries/10586/ERROR-RISEUP-K9-MAIL.png](url)

**Comment by kradan** [comment]
Thanks for your feedback and the explanation (I overread 'point 6'
before). Does the committed change solve the issue?

BTW It would be great to have images in other lanuages as well (at least
english).

**Comment by aldobelus0** [comment]
> Thanks for your feedback and the explanation (I overread 'point 6'
before). Does the committed change solve the issue?

Sure, it works for me, at least. 

![riseup-error](https://cloud.githubusercontent.com/assets/15985449/17665439/47585286-62fb-11e6-9773-5a10701943fa.png)

Done!

**Comment by kradan** [comment]
Thanks! (added pull request #374)
