### ISSUE TITLE
Rewrite the IRC section of the contact page

### ISSUE THREAD

**Issue by just1602** [riseupnet/riseup_help#394]
We should rewrite the IRC section of the contact page to make it as clear as possible and higlight informations like server adress, port, channel and not only the warning in bold that highlight that we have to use the port 6697.

If you want, you can assign it to me. I'll do it when I'll have some free time. :)

**Comment by just1602** [comment]
When I'll have some free time, I'll practice my spanish and translate the es page. :)

**Comment by willmaida007** [comment]
Please can someone help me with invitation code for riseup?

**Comment by just1602** [comment]
@willmaida007 normally you have to know someone who'll give you an invitation code. Have you a friend or someone you know who use riseup? It's the best way to get one.

**Comment by willmaida007** [comment]
Thanks for the response. I don't know anyone that uses riseup. I read about
riseup on the internet and really like it. I will appreciate if you can
help me with a registration code.

**Comment by willmaida007** [comment]
is that an invite code?
