### ISSUE TITLE
R.I.P Riseup.net Canary

### ISSUE THREAD

**Issue by ghost** [riseupnet/riseup_help#404]
You failed to feed(update) your canary. Therefore, ALL RISEUP USERS MUST STAY AWAY FROM THIS
PROVIDER BECAUSE this service is compromised.

**Comment by GitHubHatesTor** [comment]
https://riseup.net/en/canary

**Comment by Sigafoos** [comment]
It was updated 16 Feb 2017:

> Q: Why didn't you update your canary on time in the winter of 2016?
>
> A: The canary was so broad that any attempt to issue a new one would be a violation of a gag order related to an investigation into a DDoS extortion ring and ransomware operation[0]. This is not desirable, because if any one of a number of minor things happen, it signals to users that a major thing has happened.

So, this can likely be closed? If you don't trust this update then there's nothing any PR could do to fix that, right?

**Comment by elijh** [comment]
the canary is updated, so i will close this issue.
