### ISSUE TITLE
Use dirmngr in OpenPGP best practices

### ISSUE THREAD

**Issue by IvanFon** [riseupnet/riseup_help#449]
Some of the options used in the OpenPGP best practices are deprecated, for example:

`gpg: keyserver option 'ca-cert-file' is obsolete; please use 'hkp-cacert' in dirmngr.conf`

It seems like the page needs to be updated to use `dirmngr` for some configuration.

**Comment by micah** [comment]
Hi Ivan,

Ivan Fonseca <notifications@github.com> writes:

> Some of the options used in the OpenPGP best practices are deprecated, for example:
>
> `gpg: keyserver option 'ca-cert-file' is obsolete; please use 'hkp-cacert' in dirmngr.conf`
>
> It seems like the page needs to be updated to use `dirmngr` for some configuration.

You are absolutely right. The gpg2 release has incorporated many of
these 'best practices' and as a result the document needs an overhaul.

Incremental changes could eventually get us there, if you would like to
contribute pull requests, we would be happy to merge them.

**Comment by IvanFon** [comment]
I'd love to contribute, but unfortunately I'm new to GPG and I'm having a tough time finding good, up-to-date info. It would be great if someone with more experience with GPG could contribute, but I might make some changes myself if I can.

**Comment by micah** [comment]
Ivan Fonseca <notifications@github.com> writes:

> I'd love to contribute, but unfortunately I'm new to GPG and I'm
> having a tough time finding good, up-to-date info. It would be great
> if someone with more experience with GPG could contribute, but I might
> make some changes myself if I can.

Understandable! Any contributions you can make are very welcome.

**Comment by anarcat** [comment]
this is to at least somewhat overlap with #294 - is there anything else than the `ca-cert-file` option that needs changing here?

**Comment by kradan** [comment]
From [this list](https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration-Options.html) following options are deprecated

> --keyserver name
>     This option is deprecated - please use the --keyserver in dirmngr.conf instead. 
> 
> http-proxy=value
>     This option is deprecated. Set the proxy to use for HTTP and HKP keyservers. This overrides any proxy defined in dirmngr.conf.

Also there is https://www.gnupg.org/documentation/manuals/gnupg/Deprecated-Options.html but none of them were mentioned in the guide.

I am about to prepare a commit that shortens the whole keyserver section. Shall we keep suggestions for gnugpg older then 2.1 in a separate legacy guide?

**Comment by micah** [comment]
The gpg best-practices guide has been deprecated, so closing this issue.
