### ISSUE TITLE
update key splitting procedure for GnuPG 2.1

### ISSUE THREAD

**Issue by anarcat** [riseupnet/riseup_help#453]
The [key splitting procedure](https://riseup.net/en/security/message-security/openpgp/gpg-best-practices#keep-your-primary-key-entirely-offline) is designed for GnuPG 1.4 and should be update for GnuPG 2.1.

**Comment by kradan** [comment]
In #147 a pull request from 2014 micah, elijah and others pointed out

> I think that mentioning in the best-practices that one can do such a thing is useful, however putting the technical details in the document itself seems a little too much.

> how about we remove some of the key management stuff from the best practices page and update the key management page that is already started?

> most of the content on the OpenPGP Best Practices page is actually about key management (with a few exceptions, such as the "Using Free Software" section), and thus would also possibly make more sense being on the "Managing OpenPGP Keys" page instead of here
> one thing that might be helpful (in addition to moving a lot of the key management content from "Best Practices" to there), is to remove the GUI instructions for GPG key generation, configuration, etc altogether, and just have one single set of clear instructions for how to use the gpg command line client, because the usage of the command-line client is independent of the OS.

If no one objects following these suggestions I'd do the following:
* Strip down "3. Selecting a keyserver and configuring your machine to refresh your keyring." as most of the points became defaults in gnupg 2.1
* Move "4. Key configuration." to the beginning of [Managing OpenPGP Keys](https://riseup.net/en/security/message-security/openpgp/gpg-keys)
* Remove "5. Putting it all together." as it has become obsolete.

**Comment by micah** [comment]
We have deprectated the gpg security guide, so closing this issue!
