### ISSUE TITLE
mention elliptic curve algorithms in best practices guide

### ISSUE THREAD

**Issue by anarcat** [riseupnet/riseup_help#454]
The best practices guide could suggest considering ECC subkeys since they are now supported in 2.1. They are faster, which is very useful for security tokens. Note that if there's a RSA and ECC key on a key, GnuPG 1.4 will do the right thing and choose the one that works (e.g. use RSA if it doesn't support ECC)...

**Comment by micah** [comment]
We have deprecated the best practices guide, and instead tell people to use the defaults now, so closing this issue!
