### ISSUE TITLE
Donate Bitcoin link doesn't work

### ISSUE THREAD

**Issue by jorgesumle** [riseupnet/riseup_help#458]
When I click on the donate button `Grab a bitcoin address` it says:
```
Not Found

The requested URL /new-bitcoin-address was not found on this server.
```

**Comment by elijh** [comment]
fixed. we had an issue with our wallet.

**Comment by jorgesumle** [comment]
I get the same error. Am I doing something wrong?

![captura de pantalla de 2017-10-21 13 06 18](https://user-images.githubusercontent.com/14212780/31851185-ae9dbd32-b660-11e7-9663-f4fa4b10b384.png)

**Comment by elijh** [comment]
my bad. *actually* fixed now.

thanks

**Comment by jorgesumle** [comment]
Great, finally I'm able to donate. Thanks!
