### ISSUE TITLE
Evolution manual may be outdated

### ISSUE THREAD

**Issue by kradan** [riseupnet/riseup_help#473]
(also for other clients)
The text contains "UNCONFIRMED" - the described behavior should be checked and updated if necessary.

**Comment by baldurmen** [comment]
@kradan Yo, I see that you did a commit to solve this issue on your fork! Could you please make a PR so we can merge it?

**Comment by kradan** [comment]
hey! this commit is part of riseupnet#523 which i still need to finish (sorry for the long delay!). do you want me to cherry-pick it on top of master?
