### ISSUE TITLE
HTML and CSS errors

### ISSUE THREAD

**Issue by kradan** [riseupnet/riseup_help#475]
Some may be related to [amber](https://github.com/leapcode/amber)
* [HTML](https://validator.w3.org/nu/?doc=https%3A%2F%2Friseup.net%2F)
> Error: No p element in scope but a p end tag seen.
> Warning: The name attribute is obsolete. Consider putting an id attribute on the nearest container instead.
* [CSS](https://jigsaw.w3.org/css-validator/validator?uri=riseup.net&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en) (9 errors)

**Comment by elijh** [comment]
it turns out the extra <p> is the fault of textile, and i can't figure out a way to work around it. for now, i have switch to haml for the front page.

the css errors do not appear to be correct, according to msn.
