### ISSUE TITLE
Revenge (porn) and list subscribing

### ISSUE THREAD

**Issue by distimica** [riseupnet/riseup_help#492]
Back in 2008 my ex-husband got angry at me. He decided to harass me online. That is bad. 

So far are you guys with me? 

So please tell me why, after a decade of this am I stil receiving, filtering and trashing hundreds of emails from riseup.net every month? 

Can you please help me stop this. His actions might have stopped after the cops got involved, but he still harasses me with every list email that I have never subscribed for that I see on my trash folder. 

I can provide proof of ownership of the email account, proof of identity, proof that I reported him to the police in Brazil,  whatever you guys need to believe me and stop this. Please.

**Comment by disturbio** [comment]
Hey,

This is something we need to take care, but it's not possible for us to do support over github.com. Can you open a ticket at https://support.riseup.net indicating your e-mail or forward some of the things you are receiving to abuse@riseup.net?

I'm deeply sorry for the troubles we have been allowing to happen over the last 10 years, and I have questions about why this was not resolved before, but please open a support ticket to be able at least stop this terrible situation

**Comment by disturbio** [comment]
This talk was moved to our support system. Closing this ticket.
