### ISSUE TITLE
Riseup Certiticate Validation text should match GPG output.

### ISSUE THREAD

**Issue by bill-mcgonigle** [riseupnet/riseup_help#506]
Currently at:

https://riseup.net/en/security/network-security/certificates#verify-riseups-certificate

the instructions say:
```
You should get output that says:
gpg: Good signature from “Riseup Networks <collective@riseup.net>”
```

but GPG says:
```
gpg: Good signature from "Riseup Treasurer <treasurer@riseup.net>"
gpg:                 aka "Riseup Networks <collective@riseup.net>"
```

The fingerprints match and there are many signatures on the key, but there shouldn't be ambiguity in a certificate verification procedure.  I was also surprised to get the treasurer's key in the first step.

I could make a pull request with updated/clarified instructions, but I don't know if it's the right thing to do or if this is an unexpected situation.

**Comment by wiktor-k** [comment]
Hmm... sounds like a good idea. I wonder if the commands in instructions couldn't be shortened to just this:

```
curl -s https://riseup.net/certificates/riseup-signed-certificate-fingerprints.txt | gpg --auto-key-retrieve --verify --output -
```

And then checking if the output is OK (`Good signature` and `Primary key fingerprint: 4E07 9126 8F7C 67EA BE88  F1B0 3043 E2B7 139A 768E`).

**Comment by kradan** [comment]
I like the short notion but  I have a problem with [textile](https://www.promptworks.com/textile/html-integration-and-escapement#block-code) as the bc. notion will create an output that cannot be used in a terminal as it inserts '>' at the beginning of the second line. The code

`bc. curl -s https://riseup.net/certificates/riseup-signed-certificate-fingerprints.txt | gpg --auto-key-retrieve --verify --output -`

creates the HTML code
```
<pre><code>curl -s <a href="https://riseup.net/certificates/riseup-signed-certificate-fingerprints.txt">riseup.net/certificates/riseup-signed-certificate-fingerprints.txt</a> | \
gpg --auto-key-retrieve --verify --output -</code></pre>
```

It looks fine in the browser but when I copy it into a terminal (which is not a good idea anyway, because a malicious page could contain manipulated code) it shows:

```
$ curl -s riseup.net/certificates/riseup-signed-certificate-fingerprints.txt | \
> gpg --auto-key-retrieve --verify --output -
```

and the command will fail. As you can see "https://" was stripped, but that is not the actual problem. It works well with wget but not curl because it does not automatically follow the redirect:

```
$ wget -qO - riseup.net/certificates/riseup-signed-certificate-fingerprints.txt | gpg --auto-key-retrieve --verify --output -As of October 11, 2017, the following are the fingerprints for Riseup's certificates:                           

 .  *.riseup.net, riseup.net
        SHA-256 fingerprint:
                ab1757631d84ba6f77cc0784fcbdccedd6268c217dbe625d53aa976d1de74123                                


!!!
NOTE: Certificates for help.riseup.net, riseup.net and www.riseup.net are                                       
auto-renewed Let's Encrypt certificates. They are renewed approximately 3                                       
months and we do not list their fingerprints here
!!!
gpg: Signature made Wed Oct 11 21:13:32 2017 CEST
gpg:                using RSA key 4E0791268F7C67EABE88F1B03043E2B7139A768E                                      
gpg: Good signature from "Riseup Treasurer <treasurer@riseup.net>" [unknown]                                    
gpg:                 aka "Riseup Networks <collective@riseup.net>" [unknown]                                    
gpg: WARNING: This key is not certified with a trusted signature!                                               
gpg:          There is no indication that the signature belongs to the owner.                                   
Primary key fingerprint: 4E07 9126 8F7C 67EA BE88  F1B0 3043 E2B7 139A 768E                                     

$ curl -s riseup.net/certificates/riseup-signed-certificate-fingerprints.txt | gpg --auto-key-retrieve --verify --output -                                                                                              
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
$ curl -s riseup.net/certificates/riseup-signed-certificate-fingerprints.txt
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://riseup.net/certificates/riseup-signed-certificate-fingerprints.txt">here</a>.</p>
</body></html>
```
So I will stick with wget until a workaround turns up.

**Comment by wiktor-k** [comment]
Curl will follow redirects when `-L` is used, actually some people use the `-sSL` mnemonic (silent, show-error, follow redirects).

But the lack of initial `https://` is a bummer 😢 Maybe [`.notextile`](https://txstyle.org/doc/6/no-textile-processing) can be used?

**Comment by kradan** [comment]
@wiktor-k thanks for the info, will use "curl -sSL", unfortunately none of the notextile syntax options changes the behaviour, https:// is always stripped from the visible code and turned into a link.
