### ISSUE TITLE
parcimonie fails with gnupg 2.1

### ISSUE THREAD

**Issue by kradan** [riseupnet/riseup_help#522]
Since gnupg 2.1 [parcimonie](https://gaffer.ptitcanardnoir.org/intrigeri/code/parcimonie/) has issues to request keys

```
gpg: keyserver receive failed: No data                                                                           
 at /usr/share/perl5/App/Parcimonie/Daemon.pm line 350.                         

```
I got an elaborate answer in #gnupg:

> if all it does is randomise (a bit) the retrieval of key updates then we might add something like that that we actually know. It's not planned for it, but it could be included as an example under another part ... specifically GPGME bits.
Why does a perl script that just does a bit od pseudo-randomising need to be so big and with so many components? most of which appear to be trying to fix problems that don't exist and implementing things that are already built into tor.
The best way to genuinely be certain no one knows which key or keys you're interested in is easy (but may require a fair bit of disk). just run your own keyserver as part of the pool. implementing a tor socks server is a bit redundant and the tor daemon has had that for a very long time now.

In times of hkps parcimonie might not be that important anymore, so we could remove that part alltogether.

**Comment by micah** [comment]
kardan <notifications@github.com> writes:

> Since gnupg 2.1 [parcimonie](https://gaffer.ptitcanardnoir.org/intrigeri/code/parcimonie/) has issues to request keys
>
> ```
> gpg: keyserver receive failed: No data                                                                           
>  at /usr/share/perl5/App/Parcimonie/Daemon.pm line 350.                         
>
> ```
> I got an elaborate answer in #gnupg:
>
>> if all it does is randomise (a bit) the retrieval of key updates then we might add something like that that we actually know. It's not planned for it, but it could be included as an example under another part ... specifically GPGME bits.
> Why does a perl script that just does a bit od pseudo-randomising need to be so big and with so many components? most of which appear to be trying to fix problems that don't exist and implementing things that are already built into tor.
> The best way to genuinely be certain no one knows which key or keys you're interested in is easy (but may require a fair bit of disk). just run your own keyserver as part of the pool. implementing a tor socks server is a bit redundant and the tor daemon has had that for a very long time now.
>
> In times of hkps parcimonie might not be that important anymore, so we could remove that part alltogether.

I requested this feature in the g10code bug tracker some time ago
(https://dev.gnupg.org/T1235), but it is only stalled.

an easy way to do this is:

```
#!/bin/bash

while true
do
	for fingerprint in $(gpg --list-keys --with-colons --with-fingerprint | grep --after-context "1" "^pub" | grep "^fpr" | cut -d ":" -f "10" | sort --random-sort)
	do
		sleep $(( (RANDOM % 1000) + 300))
		gpg --batch --no-tty --no-auto-check-trustdb --refresh-keys "$fingerprint" 2> /dev/null
	done
done &
```

**Comment by kradan** [comment]
thanks, @micah. I will replace the recommendation for parcimonie with this script then.

**Comment by anarcat** [comment]
let's please not do this just yet. parcimonie is still important and i do think submitting requests through tor is an important use case to avoid profiling users. as far as I can tell, the provided script does not use tor at all...

**Comment by disturbio** [comment]
gnupg has tor support now, which will work not only on refresh but also in fetching keys from keyservers or using a web key service. if tor support is important, using the one provided by gnupg itself that will work in more scenarios...

**Comment by anarcat** [comment]
On 2018-09-17 17:38:36, guido wrote:
> gnupg has tor support now, which will work not only on refresh but also in fetching keys from keyservers or using a web key service. if tor support is important, using the one provided by gnupg itself that will work in more scenarios... 

that is what parcimonie does as well. if parcimonie fails, it's not
parcimonie's fault, but gpg's and that script will fail in exactly the
same ways, unfortunately.
