### ISSUE TITLE
no HTTPS for seaccp.org

### ISSUE THREAD

**Issue by Neustradamus** [riseupnet/riseup_help#590]
No HTTPS for seaccp.org.

But why you have not done a labs.riseup.net?

**Comment by sqil2019** [comment]
The seaccp.org page redirects to an old riseup labs page.

**Comment by disturbio** [comment]
This website doesn't exists anymore. The dns records for it were removed yesterday. I don't know if it will have a website again or not, but for now I'm closing this.
