### ISSUE TITLE
Security Contact should be mentioned

### ISSUE THREAD

**Issue by daniel-barrows** [riseupnet/riseup_help#592]
I'm not seeing a security contact anywhere on riseup.net. It is good practice for security-conscious groups to have a private means of contacting a security team. At the moment, the only option I see is the [public support ticket system](https://support.riseup.net/en/topics/new).

Specifically, I would like to see a security contact linked from this page:
https://riseup.net/en/security

**Comment by sqil2019** [comment]
Good point @daniel-barrows  ! There are contact points listed on https://riseup.net/en/about-us/contact along with a pgp key for the collective account, but I agree it would be a good idea to duplicate that contact info on that page.

**Comment by sqil2019** [comment]
This page is more generic help about security, and not specifically about Riseup, but it does make sense that someone might be looking here for this kind of contact.

I made a very small proposed change that could add a simple direction to the appropriate way to contact Riseup, without it being distracting to the overall direction of the page.
