### ISSUE TITLE
German Translation: 'Sending Mail'

### ISSUE THREAD

**Issue by RainerBielefeld** [riseupnet/riseup_help#600]
Currently \riseup_help-master\pages\lists\list-user\sending-mail\de.text is missing. I will create translation based on en.text next days

**Comment by RainerBielefeld** [comment]
I am really working on this, but have too many other activities ...  😥
Half text is translated now.

**Comment by RainerBielefeld** [comment]
Here is my translation. Unfortunately I havenn't a clue how to test the syntax. Bu If you think it's appropriate, you can integrate the new text and I will do some tests the same day.
[de.text.txt](https://github.com/riseupnet/riseup_help/files/3291675/de.text.txt)
Please drop the tailing ".txt" form the file name of \riseup_help-master\pages\lists\list-user\sending-mail\ file, I had to add that extension because github would not accept the original file name.

May be you can assign me to this issue? And tell my how I can contribute patches in a correct way?

**Comment by RainerBielefeld** [comment]
"Sending Mail" will have be modified to "Emails Senden" at https://riseup.net/de/lists/list-user/sending-mail when translation goes online.

https://riseup.net/de/lists/list-user/subscribing will be my next translation project.

**Comment by taggart** [comment]
Hi!

Thanks for the translation! One thing you can do to make this sort of thing trivial to be added is by making a "Pull Request". This is sort of explained at https://github.com/riseupnet/riseup_help#advanced-method---using-git-and-amber

This makes it easier for people to review/discuss your changes and once they are complete just click a button to approve them (and then you get credit in the git history too). If you are up for that cool, if not then someone can take what you provided and do a pull request, just let us know.

Thanks
