### ISSUE TITLE
how to start pkg from commandline

### ISSUE THREAD

**Issue by bgrayburn** [riseupnet/riseup_help#692]
thank you for all you do, I'm trying to spin up risevpn on a headless machine using the pkg version, but  this:
```
$ /usr/bin/riseup-vpn 
2020/04/29 23:13:59 Can't configure logger:  open /home/bgrayburn/.config/leap/systray.log: no such file or directory
2020/04/29 23:13:59 firewall stop
Unable to init server: Could not connect: Connection refused

(riseup-vpn:31291): Gtk-WARNING **: 23:13:59.567: cannot open display:
```
if there is a way to do this could you put it in the docs please?

**Comment by disturbio** [comment]
Hi,

This is a LEAP related request, but in practice there is no way to do this with the riseup-vpn client (yet). This feature is in the works and it will be announced when is possible to do.

In solidarity,
g.
