### ISSUE TITLE
Make it clear that the list of « radical servers » is not curated by the Riseup collective

### ISSUE THREAD

**Issue by gagzzz** [riseupnet/riseup_help#744]
Hi,

Some people tend to refer to the [list of Radical Servers](https://riseup.net/security/resources/radical-servers) as a list of trusted providers.
This is dangerous and it should be clear that riseup doesn't deeply check the list nor trusts every server listed.

For example:
- Framasoft is bound to french surveillance laws and don't engage to fight police requests. Their services are here to show that decentralisation is possible. They don't fit in the "radical left", even though many of them are real nice, the collective is not engaged in radical left actions, as far as I know.
- Greennet says users must respect the law: https://www.greennet.org.uk/about/terms-and-conditions
- no-log.org has been answering some police requests in the past, and is now closed to new subscribers notably because of a lack of maintenance.

If people at riseup agree with that, i could submit a PR stating something like that.

**Comment by micah** [comment]
On 2021-04-06 03:40:27, gagz wrote:
> Some people tend to refer to the [list of Radical Servers](https://riseup.net/security/resources/radical-servers) as a list of trusted providers.
> This is dangerous and it should be clear that riseup doesn't deeply
> check the list nor trusts every server listed.

Yeah, I agree.

>
> For example:
> - Framasoft is bound to french surveillance laws and don't engage to fight police requests. Their services are here to show that decentralisation is possible. They don't fit in the "radical left", even though many of them are real nice, the collective is not engaged in radical left actions, as far as I know.
> - Greennet says users must respect the law: https://www.greennet.org.uk/about/terms-and-conditions
> - no-log.org has been answering some police requests in the past, and is now closed to new subscribers notably because of a lack of maintenance.
>
>
> If people at riseup agree with that, i could submit a PR stating something like that.

i think it makes sense to clarify that they are projects we are not
actually endorsing but are projects that are different from how things
work on the internet normally, like their focus is not on money.

if you want to draft something up, we'd be happy to check it out!

**Comment by elijh** [comment]
Originally, we pretty much knew and trusted every group on the list, but over time there were pull requests for adding groups. It seemed like a good idea at the time to let anyone who self identified as a radical autonomous server project to let themselves be included if they wanted to be.

I don't have a strong opinion one way or the other. I like to let groups write their own description and I don't want to put editorial comments on the entries. It is pretty useful to have a list, even if it is now very incomplete, and I guess I would be more in favor of saying these are not necessary groups we are endorsing or recommending you trust (although in practice the majority are groups that we do know well and trust).
