### ISSUE TITLE
Decide what to do about the OTR page

### ISSUE THREAD

**Issue by taggart** [riseupnet/riseup_help#781]
Back in 2021, riseup stopped providing XMPP chat services and we also [dropped the chat help pages](https://github.com/riseupnet/riseup_help/commit/849d3afac2fac100bec23801009da0093342bf92). But the pages in security/message-security/otr/ still refer to riseup's pidgin tutorial under the missing chat directory.
Rather than fix these dead links, probably the whole otr directory should go away?
It also automatically gets included on the message-security page, but that will resolve itself on rebuild once the otr directory is gone.
Right now on amber rebuild we 24 warning messages about the dead links.
Opinions?

**Comment by just1602** [comment]
I'm a simple user, but I'd say riseup should probably drop this page too. Since you're not offering XMPP service anymore and since the weechat otr plugin was not working with python 3 the last time I check, it's probably better to drop them then keep them and let them get outdated over time.

**Comment by micah** [comment]
+1 to @just1602

**Comment by just1602** [comment]
The OTR pages have been removed in e7e2180b8edc78fe688794c4dedfe82ed9b84dbd.

**Comment by micah** [comment]
thanks @just1602 !
