### ISSUE TITLE
Errors in pad history

### ISSUE THREAD

**Issue by dhowe** [riseupnet/riseup_help#787]
Not sure if this is the proper place for this ticket, but it seems the history function is currently broken on https://pad.riseup.net/

This is crucial as there appears to be no other way to restore accidentally overwritten data  (as in the case we are experiencing)

<img width="606" alt="Screenshot 2022-06-07 at 7 13 17 AM" src="https://user-images.githubusercontent.com/737638/172264591-6890e22b-33db-4983-8ec4-aa7c0ef562de.png">

This occurs on current version of both Firefox and Chrome on OS X Big Sur
thanks

**Comment by just1602** [comment]
I'd suggest you to open a ticket on https://support.riseup.net
