### ISSUE TITLE
Look of h2 title pangea.org is broken

### ISSUE THREAD

**Issue by nappex** [riseupnet/riseup_help#789]
Page: https://riseup.net/en/security/resources/radical-servers

1. formatting of h2 title of pangea.org does not look as rest of titles on that page. Instead of h2 appearance, you will find raw text: 
```
>>>>>>> refs/pullreqs/765
h2. pangea.org
```
2. pangea.org is missing in TOC of page
3. load page as https://riseup.net/en/security/resources/radical-servers#pangea or https://riseup.net/en/security/resources/radical-servers#pangeaorg does not work as user expect.

used browsers: Safari, Firefox
OS: macOS

*Note:*
I've tried to fix it, but source code on github looks fine see:
https://github.com/riseupnet/riseup_help/blob/6f3dcb242cfd84b1aa2e0c73e458afa6d858bb5c/pages/security/resources/radical-servers/en.text#L281
So maybe there is a problem when source code is generating to html. If you inspect the page, then you can see pangea is formatted as `<p>` html tag instead of `<h2>` tag.

**Comment by easingthemes** [comment]
It's a leftover from merge conflict. But I've checked all PR's around `765` and nothing.
Totally strange issue.

**Comment by taggart** [comment]
I tracked this down and cleaned it up. Thanks for the report!
