### ISSUE TITLE
does riseup mail support custom domain?

### ISSUE THREAD

**Issue by braboobssiere** [riseupnet/riseup_help#794]
or is there any plan if not?

**Comment by elijh** [comment]
This is likely a feature that is coming soon, depending on several factors. Most of the technical work has been done, but Riseup has not decided exactly the best way to make this available and how to pay for it.

**Comment by kyeastmood** [comment]
Hi! Has any progress been made on this issue? This would be a great addition.

**Comment by DangerZoneDuchess** [comment]
@elijh , interested too :) issue is closed, but documentation does not indicate it's supported :)
