### ISSUE TITLE
Cannot get support anywhere

### ISSUE THREAD

**Issue by 173236** [riseupnet/riseup_help#805]
The website https://0xacab.org/ will not let me create an account, it gives me the following error message: "Email is not allowed for sign-up. Please use your regular email address. Check with your administrator." I can't find the ticket page for the Riseup site, nor can I find the email. The main bug im trying to report is that it will not let me connect at all.

**Comment by just1602** [comment]
Normally you can't create an account on 0xacab.org with a gmail, hotmail or any big corp provider, tho. But I'm not a member of the riseup collective, so I don't know the whole list of rules.
