### ISSUE TITLE
get new riseup mail codes

### ISSUE THREAD

**Issue by Pudding26** [riseupnet/riseup_help#818]
Hello notsure if this si the correctplatform but I could not find a different way of getting in contact.

Since you understandably disabled a lot of accounts to create new invite codes due to spam issues it is not possible forourcollective to generate new invite codes.

We are a fairly big collective and have multiple E-mail accounts for the collectives in order to not have to many informations in a single account, we are running out of Addresses and I was wondering if there is a way to be able to create new Mail adresses and get a permit or a bunch of invite codes.

thank you and alerta

**Comment by just1602** [comment]
for this kind of issue, please open a ticket at https://support.riseup.net
