### ISSUE TITLE
Invite codes are sold

### ISSUE THREAD

**Issue by marek22k** [riseupnet/riseup_help#821]
Hello,

I asked the Riseup Collective some time ago if I could get an invite code. This was declined. I then asked if it wasn't bad that invite codes are sold (for money). Despite several messages, I still haven't received an answer.

>
On Fri, 3 Nov 2023 12:17:38 -0700
Riseup Collective <collective@riseup.net> wrote:

>  Hi,
> 
> We are sorry, but the only way to get an account currently is by one invite from a riseup user. Spammers were abusing the previous system making it useless for our users are we were constantly blocked by other providers. Until we can find a way to defeat those spammers, you will need to find a riseup user and get an invite from them :(  

That's a shame to hear.

> We don't give out invite codes.  

Is there any portal (e.g. IRC) where I could ask a RiseUp user?

I don't know if it's already known, but while searching for an invite
code I came across some sites that sell invite codes for money. (see
attached screenshot for example) I think this somewhat defeats the
purpose.

> 
> If you cannot acquire an invite code, or if your interest is in a service like riseup rather than specifically what riseup itself has to offer, you may want to look at our list of similarly minded radical servers (https://riseup.net/en/security/resources/radical-servers).  

Thank you for the list. There are some really interesting services on
it! 

> 
>  In solidarity,
>  - riseup collective
> 
> On 10/31/23 10:54, Marek Küthe wrote:  
> > Hello,
> > 
> > I am interested in an account with you. However, when I try to create
> > an account, it says I need an "Invite Code". How can I get such an
> > Invite Code? I don't know any person who is already with RiseUp who
> > could give me one.
> > 
> > I would be very happy to get an answer!
> > 
> > With kind regards
> > Marek Küthe
> >     

![Screenshot at 2023-11-03 23-10-54](https://github.com/riseupnet/riseup_help/assets/46723399/6f0f2e4b-235a-4720-b4a4-bf616502bbaa)

**Comment by just1602** [comment]
Hello,

Yes, this is known that some riseup users have sold invite codes in the past, and this is one of the reason why invite creation are more restricted than before.

The best way to get an invite is to get involve with local activist groups of your region. You'll likely find someone who has an account and who can create an invite code.

Otherwise, you can browse [https://riseup.net/radical-servers](https://riseup.net/radical-servers) to find other collectives who provide similar services as riseup.
